apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-configs
  namespace: event-portal
data:
  additional.yml: |
    - job_name: 'event-backend'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: backend
      metrics_path: /metrics
      scrape_interval: 15s
